### ISSUE TITLE
Fatal error: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by crebbo** [mavdi/grunt-cucumberjs#10]
It would appear that 'Background: ' steps do not have a result object and these are still processed when generating the report.

That said, for the purpose of report generation it would be nice to at least have reference to what the Background ran was. I would have through these should still have a result object, since these pre conditions could still fail for various reasons

e.g:

Background Step (no result object):
```
...
"elements": [
      {
        "name": "User is already on Sign In Page",
        "keyword": "Background",
        "description": "",
        "type": "background",
        "line": 7,
        "steps": [
          {
            "name": "I visit the Sign In Page",
            "line": 8,
            "keyword": "Given "
          }
        ]
      }
...
```

Scenario Step:
```
.....
"steps": [
          {
            "name": "I visit the Sign In Page",
            "line": 8,
            "keyword": "Given ",
            "result": {
              "duration": 546019,
              "status": "passed"
            },
            "match": {}
          }
....
```

Error caused when processing this part of task/cucumber.js
```
            if(step.result.status === 'passed') return element.passed++;
            if(step.result.status === 'failed') return element.failed++;
            if(step.result.status === 'undefined') return element.notdefined++;
```

**Comment by iceicerickert** [comment]
any updates on this (workaround or fix)? I'm getting the same error :+1: 
I need to put the background steps in the json report

**Comment by gkushang** [comment]
Closing this issues since latest releases of `cucumber` adds the `result` object to the background step and it is being captured in the reports
