### ISSUE TITLE
Issue downloading latest grunt-cucumberjs version [V1.0.0]

### ISSUE THREAD

**Issue by shekarls** [mavdi/grunt-cucumberjs#100]
I see following error installing grunt-cucumberjs v1.0.0 
```
npm ERR! node v4.6.1
npm ERR! npm  v3.10.10
npm ERR! code ETARGET
npm ERR! notarget No compatible version found: grunt-cucumberjs@1.0.0
```

**Comment by gkushang** [comment]
@shekarls Can you try with default npm registry?

```npm i grunt-cucumberjs@latest  --registry https://registry.npmjs.org``` 

Let us know what you get.

**Comment by gkushang** [comment]
@shekarls 

I assume you were able to download the latest version. Please reopen the issue if you have any further feedback.

Thanks!
