### ISSUE TITLE
Issues resolved in fork, waiting on response to PR

### ISSUE THREAD

**Issue by caseygoodhew** [mavdi/grunt-cucumberjs#102]
https://github.com/mavdi/grunt-cucumberjs/compare/master...caseygoodhew:master

@yellamillis has had a PR open for a 11 days. We've made a couple of additional improvements, but we needed to keep work progressing, so we've forked and re-packaged to https://www.npmjs.com/package/grunt-cucumberjs-fork

I'll be happy to merge changes back in if this repo is still active. If not, I'm happy to run the fork as well.

**Comment by gkushang** [comment]
@caseygoodhew Apologies for delay response. PR's are merged and published with the version `v1.0.1`.

**Comment by caseygoodhew** [comment]
Thanks! Glad to see that the repo is still active. I have a couple of other changes that we incorporated - I'll unpick a couple of things and create an additional PR in the next few days. (and kill our npm -fork package to avoid confusion)

**Comment by gkushang** [comment]
Sounds great!

**Comment by caseygoodhew** [comment]
@gkushang https://github.com/mavdi/grunt-cucumberjs/pull/104
