### ISSUE TITLE
Unable to parse cucumberjs output into json.

### ISSUE THREAD

**Issue by j2ro** [mavdi/grunt-cucumberjs#15]
I am getting the following error intermittently when running my cucumber tests, and producing a HTML report via grunt-cucumberjs:

"Unable to parse cucumberjs output into json."

It looks like that this is thrown on line 88 of cucumber.js.

I think this is happening because when my cucumber test suite finishes, it runs an After block, which in turn writes to sysout. This output in turn is then getting appended to the end of the JSON output, and thus is no longer valid JSON.

**Comment by mavdi** [comment]
this should be fixed with latest cucumber
