### ISSUE TITLE
Mixed content in bootstrap and foundation reports

### ISSUE THREAD

**Issue by simonomis** [mavdi/grunt-cucumberjs#27]
The &lt;script&gt; and &lt;style&gt; elements use http:// urls which means they fail to load when the report is served over https because of mixed content security policy. This means the collapsible parts of the report don't work.

They should either omit the protocol part of the url or use https everywhere.

**Comment by mavdi** [comment]
This should have fixed it https://github.com/mavdi/grunt-cucumberjs/pull/28
