### ISSUE TITLE
Template system used

### ISSUE THREAD

**Issue by arasevic** [mavdi/grunt-cucumberjs#38]
What template system are you using when you create the 'simple' html output for a test output? I created a script that takes the html file generated from running a test and places it in the body of an email. When I read the email on a phone it looks great - exactly to the html file generated by the test. When I look at it on a desktop or laptop it has the same text but none of the styling. Do you have any thoughts as to why this may be? I

**Comment by mavdi** [comment]
hm, it could be down to your email client blocking the external resources. I'm closing this. Reopen if you think it's something we can fix.
