### ISSUE TITLE
Doesn't save json output

### ISSUE THREAD

**Issue by mrded** [mavdi/grunt-cucumberjs#39]
Following settings don't create `my_report.json` file with report.

    grunt.initConfig({
      cucumberjs: {
        options: {
          format: 'json',
          output: 'my_report.json'
        }
      }
    });

**Comment by gkushang** [comment]
Can you try this?

```
grunt.initConfig({
  cucumberjs: {
    options: {
        format: 'html',
        output: 'path/to/report.html',
        theme: 'bootstrap ',
        saveJson: true //this will be saved Json as report.json
    }
  }
});
```

**Comment by mrded** [comment]
Is it possible to save json only?

**Comment by mrded** [comment]
it makes report.html & report.html.json files.

**Comment by gkushang** [comment]
I do not think it generates only JSON files. This module generates pretty HTML report for cucumber. JSON file is in the similar format of cucumberjs, e.g. `cucumberjs {options} -f json | tee report.json`

**Comment by mrded** [comment]
It would make sense to choose a format you want to output.

**Comment by mavdi** [comment]
since ```cucumberjs``` itself will output ```json``` I don't see the need for us to support a ```json``` only option. Closing.
