### ISSUE TITLE
Some templates use hard-coded protocol for scripts and styles

### ISSUE THREAD

**Issue by jnewc** [mavdi/grunt-cucumberjs#43]
The bootstrap theme specifically loads resources using https. This causes issues on internal systems that don't have SSL certificates.

It would be useful if they used the "//" shorthand like the Foundation template, to ensure that resources are loaded correctly.

I'd be happy to submit a PR for this.

**Comment by mavdi** [comment]
We've had a few back and forths with this. Problem being browsers don't load up the ```//``` urls if the content is not served and opened as a file locally. If there is a way of finding out if the report is being opened locally or served, and switching urls when it does so, I'd be happy to accept a PR.

**Comment by walmik** [comment]
Maybe this has already been considered but can we just use the http resource for bootstrap? It seems to exist at the same path http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css

**Comment by mavdi** [comment]
This isn't only an issue with bootstrap but also with static files. Closing.
