### ISSUE TITLE
Missing --fail-fast option

### ISSUE THREAD

**Issue by kevynb** [mavdi/grunt-cucumberjs#49]
Hello,

The fail fast option from cucumber is missing in the grunt-cucumberjs plugin.

Right now you have to use dirty tricks if you want to stop executing the test suite after a failed test like using the After hooks to exit if one scenario failed.

This is especially useful when you have lots of tests.

I've submitted the pull request #48 to solve this.

**Comment by mavdi** [comment]
Closing since PR is merged.
