### ISSUE TITLE
[feature request] execute specific scenario in file by adding a colon

### ISSUE THREAD

**Issue by kashesandr** [mavdi/grunt-cucumberjs#52]
Hey.

I faced with the problem. 

I want to rerun failed scenarios, it's already implemented in `cucumber-js` to find failed ones - https://github.com/cucumber/cucumber-js#formatters (see `rerun` formatter).

When I add the array of failed scenarios like ['feature1.feature:23', 'master.feature:11', ...] to grunt configs it doesn't handle this.

Can you implement the feature?

**Comment by gkushang** [comment]
https://github.com/mavdi/grunt-cucumberjs/pull/54 will resolve the issue.
