### ISSUE TITLE
Report doesn't get generated when scripts are executed in conjunction with webdriverio

### ISSUE THREAD

**Issue by SimitTomar** [mavdi/grunt-cucumberjs#53]
I have my Grunt file defined as below:
module.exports = function(grunt) {

    grunt.initConfig({

            webdriver: {
                test: {
                    configFile: 'tests/acceptance/wdio/conf/cuke.conf.js',
                    options: {
                        cucumberjs: {
                            options: {
                                format: 'html',
                                output: 'my_report.html',
                                theme: 'bootstrap'
                            }
                        }
                    }
                }
            }

    });

    grunt.loadNpmTasks('grunt-webdriver');
    grunt.loadNpmTasks('grunt-cucumberjs');

};

The path to the Feature file and other necessary configuration is given in the cuke.conf.js. On running the task grunt Webdriver, the scripts executed fine but no Report is generated.

Thanks
Simit

**Comment by gkushang** [comment]
@SimitTomar are you still facing the issue?

**Comment by gkushang** [comment]
@SimitTomar Closing this issue. Please try with the latest version and let us know if you are still facing this issue.

**Comment by SimitTomar** [comment]
Hey Kushang,

I switched to Gulp-protractor for generating Reports.

Thank
Simit
