### ISSUE TITLE
Erroneous tests respond as if everything ok

### ISSUE THREAD

**Issue by SirLenz0rlot** [mavdi/grunt-cucumberjs#55]
```gherkin
When I insert a reference error on one of my source files
And I run cucumber
Then I expected the job to fail
But instead, it runs no tests and Grunt says "Done, without errors."
```

it does print the error above it, with stacktrace: e.g.
`ReferenceError: sadfs is not defined`

Running cucumberjs directly would result in an exit code 1.

**Comment by gkushang** [comment]
@SirLenz0rlot it is failing scenario for reference error. Below is the report. Can you help us reproduce?

<img width="1175" alt="screen shot 2016-02-10 at 4 20 51 pm" src="https://cloud.githubusercontent.com/assets/3663389/12962175/4d35e7f8-d012-11e5-9e29-c6f72cbec0bc.png">

**Comment by SirLenz0rlot** [comment]
Closing, will reopen if I can reproduce.
