### ISSUE TITLE
support for multiple output formats

### ISSUE THREAD

**Issue by SirLenz0rlot** [mavdi/grunt-cucumberjs#56]
I'd like to see both html and console for the same tests.

If I'm correct, that's currently not possible?

**Comment by SirLenz0rlot** [comment]
The reason I'd like to have this, is to have some sort of progress indication, while waiting for my report to be generated.

**Comment by gkushang** [comment]
Sounds like a good feature to support. Thanks @SirLenz0rlot! PR https://github.com/mavdi/grunt-cucumberjs/pull/57 will add a support for multiple output formats.

**Comment by gkushang** [comment]
this is published as grunt-cucumberjs@0.8.8
