### ISSUE TITLE
support the --compiler option

### ISSUE THREAD

**Issue by travi** [mavdi/grunt-cucumberjs#58]
When using a compiler like babel, this needs to be run before the source files can be executed. Cucumber provides a [`--compiler`](https://github.com/cucumber/cucumber-js#requiring-support-files) option to support executing a compiler before running the tests. Without support for the flag, the [babel require hook](https://babeljs.io/docs/usage/require/) can be used, but this adds a load order requirement to ensure that hook is executed first.

Would it be possible to enable this option as part of the plugin?

**Comment by kashesandr** [comment]
Agree. It would be great to have a support for coffee-script.

**Comment by gkushang** [comment]
This will resolved by https://github.com/mavdi/grunt-cucumberjs/pull/61/

**Comment by gkushang** [comment]
Compiler support is added to the latest version `0.9.0` :+1:
