### ISSUE TITLE
Extract templates and report generation to separate npm module

### ISSUE THREAD

**Issue by mucsi96** [mavdi/grunt-cucumberjs#60]
It would be very helpful to extract the template and html report generation to a separate npm module with a Javascript API. I would like to use it in my https://github.com/mucsi96/nightwatch-cucumber module and I don't what to copy-past you html template related code.

Do you think it is possible?
Thanks
Igor

**Comment by mucsi96** [comment]
May the best would be to put it inside https://github.com/cucumber/cucumber-html
What do you think?
Thanks

**Comment by gkushang** [comment]
Hi @mucsi96 Thanks for the request, and sorry for the late response. 

It would be very nice to have this support in `night-watch` as well. I have few thoughts, @mavdi , please chime in what you think as well?

@mucsi96 What if we separate out the `grunt` command and provide you with the `cucumber-runner`, which would produce HTML report as well as support for parallel executions? Do you think that would fulfill your request? Let us know

**Comment by mucsi96** [comment]
@gkushang Thanks for response. [Nightwatch-cucumber](https://github.com/mucsi96/nightwatch-cucumber) is using Nightwatch.js runner which has parallel execution built in. I need a very simple API which is capable to generate html report from cucumber json formatter output. So basicly I need only the [generateReport](https://github.com/mavdi/grunt-cucumberjs/blob/master/lib/processHandler.js#L249) function.

**Comment by mavdi** [comment]
Yup this works for me absolutely. How do you want to proceed?

**Comment by mucsi96** [comment]
I see 3 ways to proceed. 
1. Is the hardest but the best for most developers :). Is to reimplement the template generation logic in Go and create a PR to https://github.com/cucumber/cucumber-pretty-formatter
2. Is to compare the template generation logic with https://github.com/leinonen/cucumber-html-report. And may be provide PR. This package is owning the `cucumber-html-report` name. I think the best for this functionality.
3. Is to create a new npm package with name `cucumber-html-reporter` or `cucumber-html-formatter` and GitHub repo. But currently we have 5 different html reporters in npm :)

**Comment by gkushang** [comment]
@mucsi96 - WIP - this seems to be working,

```
var cucumberHtmlReport = require('grunt-cucumberjs')();
....
....
  var options = {
    theme: 'bootstrap',
    outputHtml: 'tests/acceptance/report.html',
    json: 'tests/acceptance/features_report.html.json'
  };

  cucumberHtmlReport.generate(options);

```
We can PR to the external html modules and also to the cucumber-html as an additional reporting format.

Let us know what do you think about it.

**Comment by mucsi96** [comment]
I saw you created the https://github.com/gkushang/cucumber-html-reporter. That is amazing! Thank you!
