### ISSUE TITLE
Multiple formatter doesn't work for me

### ISSUE THREAD

**Issue by SirLenz0rlot** [mavdi/grunt-cucumberjs#62]
The fix for https://github.com/mavdi/grunt-cucumberjs/issues/56 doesn't work for me.
I've upgraded to the latest (0.8.8) (and verified the 'formats' option is in `tasks/cucumber.js`)

This is my config.

        cucumberjs: {
            options: {
                tags: [ "~@Pending "],
                // format: "html",
                formats: ["pretty", "html"],
                templateDir: "template",
                output: "reports/cucumber.html"
            },
            features: [],

            signoff: {
                options: {
                    tags: [ "@signoff "]
                }
            }
        },

The html report is created, but no cucumber output is shown in the console.

**Comment by SirLenz0rlot** [comment]
I verified this again from a clean environment. I can't get multiple `formats` to work in any way.
@gkushang any idea what might be (or might I be doing) wrong?

**Comment by gkushang** [comment]
Hi @SirLenz0rlot 

Did you try with below options?  It works for us. Plus, our cucumber version is `"cucumber": "0.9.5",` which has multi-formatter support,

```
	return {
			options: {
				formats: ['html', 'pretty'],
				output: 'test/acceptance/report/cucumber_report.html',
```

Let us know if it does not work.

**Comment by SirLenz0rlot** [comment]
I was on cucumber 0.9.2, but even upgrading cucumber to 0.10.2 didn't help.

It doesn't throw errors, but it doesn't print any 'pretty' output when running either.

The spawn arguments when spawning cuucmber seem to be ok.
When I do 
`node_modules/cucumber/bin/cucumber.js -t @signoff -f pretty -f json:reports/cucumber.html.json` 
I get both a json and the pretty print.

**Comment by SirLenz0rlot** [comment]
I think I found some problems, in  `processHandler.js`, `options.isHtml` is being used as a flag to 
'eat up' console logging.

This works makes things bettter for me, but may pollute the terminal for other users (?):

    cucumber.stdout.on('data', function(data) {
        grunt.log.write(data);
        if (options.isHtml) {
            if (options.debug) {
                process.stdout.write(data);
            }
            buffer.push(data);
        }
    });


The current code:
   
    cucumber.stdout.on('data', function(data) {
        if (options.isHtml) {
            if (options.debug) {
                process.stdout.write(data);
            }
            buffer.push(data);
        } else {
            grunt.log.write(data);
        }
    });

**Comment by gkushang** [comment]
@SirLenz0rlot Did you try providing multi-formatters in your CucumberJs options as shown below,

```
	return {
			options: {
				formats: ['html', 'pretty'],
```

It should pretty print the console when you run the tasks without Parallel executions. Let us know if that does not work for you.

**Comment by SirLenz0rlot** [comment]
Yes, of course I did :), as in the first post.
It doesn't for me.
Op 26 apr. 2016 5:38 PM schreef "Kushang Gajjar" <notifications@github.com>:

**Comment by gkushang** [comment]
@SirLenz0rlot We are able to pretty print with `cucumber@0.10.2`. It would be very helpful to debug if you could share any errors you see, the command you use to run tasks and `cucumberjs.js` options.

**Comment by SirLenz0rlot** [comment]
This is one of the many grunt configurations I tried in my Gruntfile.js. 
I call it with `grunt cucumberjs:signoff`

        cucumberjs: {
            options: {
                tags: [ "~@Pending "],
                formats: ["html", "pretty"],
                templateDir: "template",
                output: "reports/cucumber.html",
                saveJSon: "true"
            },
            features: [],

            signoff: {
                options: {
                    tags: [ "~@Pending", "@signoff" ]
                }
            },
      }

As mentioned before, I'm not seeing any errors, it just doesn't print any cucumber output to the terminal. 
Oh, and I'm on Ubuntu 14.04.

If you run yourself with `formats: ["html", "pretty"]`. Does your code hits the callback on `cucumber.stdout.on('data',` in `processHandler.js` ??

The code in `processHandler.js` seems to only log to the terminal (like pretty print) if `options.isHtml` is not set to true, which is the case, because I use 'html' too as a formatter.

**Comment by vidz2** [comment]
@SirLenz0rlot  I had the same issue as you. As a workaround I added debug: true in the options and it seems to print the output to console log and html report.

cucumberjs: {
        options: {
            tags: [ "~@Pending "],
            formats: ["html", "pretty"],
            debug: "true",
            templateDir: "template",
            output: "reports/cucumber.html",
            saveJSon: "true"
        },
        features: [],

        signoff: {
            options: {
                tags: [ "~@Pending", "@signoff" ]
            }
        },
  }

**Comment by SirLenz0rlot** [comment]
@vidz2  Thanks, I'm glad I'm not the only one struggling. 
I'm using the `debug` flag too, for now.

**Comment by gkushang** [comment]
closing the issue since "debug: true" prints the console with pretty formatter
