### ISSUE TITLE
No @tags information in report

### ISSUE THREAD

**Issue by Vovanchik** [mavdi/grunt-cucumberjs#64]
I first time installed this plugin and I have a question: is it possible to show somehow TAGS information in report?

I need to have grouping of features/scenarios by tags.

**Comment by gkushang** [comment]
Hi @Vovanchik 

Thanks for trying out the Plugin. Are you looking to display `Tags` information in the HTML report embedded to the Scenarios? If so, we currently do not display tags in the report but that would be great feature to add.

**Comment by Vovanchik** [comment]
Yes I am looling tags in html report.

Yuo can close issue and add this request as future improvement.

Thank you.

**Comment by Vovanchik** [comment]
Closing issue.
