### ISSUE TITLE
Can't run tests in parallel

### ISSUE THREAD

**Issue by Vovanchik** [mavdi/grunt-cucumberjs#65]
Received following error when trying to tests in parallel

Running "cucumberjs:src" (cucumberjs) task
>> cucumber parallel binary not found at path node_modules\parallel-cucumber\bin\parallel-cucumber-js
>>  NOTE: You cannot install grunt-cucumberjs without bin links on windows

Command used: **_grunt cucmberjs --parallel scenarios_**

- cucumber@0.10.2
- grunt-cucumberjs@0.9.0

What I missed?

**Comment by gkushang** [comment]
Thanks @Vovanchik for reporting. We found a bug in comparing the versions while running scenario in parallel. It is fixed and published as `v0.9.1`. Let us know if you face any issues.

**Comment by Vovanchik** [comment]
After upgrading grunt-cucumberjs version to 0.9.1 I received next error:

Running "cucumberjs:src" (cucumberjs) task
Fatal error: spawn node_modules\cucumber-parallel\bin\cucumber-parallel ENOENT

From internet surfing I found that probably some dependencies missed, but I am not sure.

Command used: _**grunt cucmberjs --parallel scenarios**_
Cucumberjs configuration:
**_        cucumberjs: {
            src: ['src/test/features/assessments.feature'],
            options: {
                format: 'pretty',
                output: 'target/cucumber-report/test-report.html',
                theme: 'bootstrap',
                executeParallel: 'true'
            }
        }_**
Package.json
**_  "devDependencies": {
    "cucumber": ">=0.10.2",
    "grunt": "~0.4.5",
    "grunt-cucumberjs": ">=0.9.1",
}_**

**Comment by Vovanchik** [comment]
It look's like this is Windows issue. Working well on Linux.

Thank you for help:+1:

**Comment by gkushang** [comment]
Nice! I noticed your output format is `pretty`, which won't generate the HTML report. You must provide `html` output formatter in order to generate the html reports. If you want to have `pretty` formatter as well then this plugin also supports multi-formatter, e.g. `formats: ['html', 'pretty']`

**Comment by Vovanchik** [comment]
Thank's for information.

Question is not related to this issue, but is it possible to specify limit of workers which are run in parallel, because option: **--worker <num of workers>**

**Comment by gkushang** [comment]
Unfortunately, `worker` option is not yet supported with the [cucumber-parallel](https://www.npmjs.com/package/cucumber-parallel) module. It's a feature request.

**Comment by Vovanchik** [comment]
Than, let's wait for new releases.

Thank you for help:+1:
