### ISSUE TITLE
Create different profiles to run tests

### ISSUE THREAD

**Issue by Vovanchik** [mavdi/grunt-cucumberjs#68]
I have several different environments local/staging/production where cucumber-js must be run.

Is it simple mechanism to define environments such a parameters baseUrl, seleniumAddress etc and run these tests from command line or I need to develop something own?

**Comment by Vovanchik** [comment]
Guys, could you please provide any information on my request?

**Comment by gkushang** [comment]
@Vovanchik it would be part of your framework as cucumber would not know about your environment. 

Few suggestions would be,
* To set the environment variable along with your `grunt` command. Based on which, load the specific Config file. We control the Stage/Env setup at our `world` constructor before launching the WebDriver.
* To pass the STAGE value as a environment variable and construct the URL dynamically, and then launch the WebDriver at `world` 

An example would be,

```
NODE_ENV=stage grunt acceptance
```
OR
```
STAGE=xxxStage grunt acceptance
```

Hope this helps!

**Comment by Vovanchik** [comment]
I thought in the same direction.

Just to be sure that there are no solutions from the box. 

Thank you
