### ISSUE TITLE
Unable to parse cucumberjs output into json.

### ISSUE THREAD

**Issue by ashkliarovjr** [mavdi/grunt-cucumberjs#69]
Due to cucumber library 1.0.0 release, when I try to generate report an error appears in console:
"Unable to parse cucumberjs output into json."

But it was ok before cucumber release.

**Comment by gkushang** [comment]
@ashkliarovjr thanks for reporting the issue. `cucumber@1.0.0` has changed the JSON formatting in the alphabetical order vars. Its fixed in the module and released as `grunt-cucumberjs@0.9.2`
