### ISSUE TITLE
Console output is not saved to HTML report

### ISSUE THREAD

**Issue by SirLenz0rlot** [mavdi/grunt-cucumberjs#77]
Earlier, the console output was saved to the HTML report.
I guess this is broken by @gkushang change: https://github.com/mavdi/grunt-cucumberjs/commit/20afb9e3d36e7b49c82e94ac0e2f0e44d175bb05 

Would be nice to have it back.

**Comment by gkushang** [comment]
It is deprecated as [cucumber-js](https://github.com/cucumber/cucumber-js) does not support console logs in the JSON reporting format. Instead, you can use `scenario.attach('text')` to log any debugging info which will be attached to the specific step in scenario, and it won't get lost in console logs.

**Comment by SirLenz0rlot** [comment]
I see.
Might as well clean up the Console Output part in the templates then

**Comment by gkushang** [comment]
Agree - we will include in the CHANGELOG and publish
