### ISSUE TITLE
html report broken

### ISSUE THREAD

**Issue by SirLenz0rlot** [mavdi/grunt-cucumberjs#79]
Yesterdays HEAD was fine,
Upgraded to HEAD today:

![image](https://cloud.githubusercontent.com/assets/1272512/16294689/6909fb58-3922-11e6-88a5-33e1bf754211.png)

My config:

        cucumberjs: {
            options: {
                debug: true,
                tags: [ "~@Pending "],
                format: "html",
                templateDir: "cucumber/report-template",
                output: "reports/cucumber.html",
            },features: [],

            signoff: {
                options: {
                    tags: [ "~@Pending", "@signoff" ]
                }
            }
        } 

The template is a sligthly modified version of the bootstrap one. the default bootstrap doesnt work either

**Comment by SirLenz0rlot** [comment]
I'm sticking to `c82f51212e5965711c32f60533a66f32b6baaedc`

**Comment by gkushang** [comment]
@SirLenz0rlot can you take a look at the [feature.tmpl](https://github.com/mavdi/grunt-cucumberjs/blob/master/templates/bootstrap/features.tmpl#L1) and update `cucumber/report-template` accordingly? 

1. https://github.com/mavdi/grunt-cucumberjs/blob/master/templates/bootstrap/features.tmpl#L1 `suite.features.featureOutput` 
2. https://github.com/mavdi/grunt-cucumberjs/blob/master/templates/bootstrap/features.tmpl#L14-L17 `feature.scenarios.`

**Comment by gkushang** [comment]
@SirLenz0rlot My apologies. I see the broken change for the Custom User Templates. We are working on fixing it. Thanks for reporting.  We will update you.

**Comment by gkushang** [comment]
@SirLenz0rlot Please ignore the above comment. I see the broken change for the Custom User Templates. We are working on fixing it. Thanks for reporting.  We will update you.

**Comment by gkushang** [comment]
@SirLenz0rlot it should be fixed with @0.10.2

**Comment by gkushang** [comment]
Hope this issues is fixed. Please reopen if you are still unable to create report.
