### ISSUE TITLE
Submit HTML reporting to cucumber-js

### ISSUE THREAD

**Issue by SirLenz0rlot** [mavdi/grunt-cucumberjs#80]
Just an idea, would it be an idea to submit the html reporting part to the `cucumber-js` project, so we help a larger audience with html reports and keep this project pure about running cucumber through `grunt`?

**Comment by gkushang** [comment]
I like the idea of extracting the HTML reporting part and process pure JSON to generate the reports. I see a huge demand of HTML reporting which can be simplified by extracting the HTML reports, and use it within this project through `grunt` - also, plug into cucumber-js project

**Comment by gkushang** [comment]
Noted 👍
