### ISSUE TITLE
formats html+pretty, pretty won't output

### ISSUE THREAD

**Issue by fboutin-pmc** [mavdi/grunt-cucumberjs#82]
Hi there,
I would like to keep the default output - aka 'pretty' - when generating the report.
I tried the `formats: ['pretty', 'html']` config but when running only html outputs.

Am I missing something here?

Thank you!

**Comment by gkushang** [comment]
Can you add option 'debug: true' to the task? It enables the console logs.

**Comment by fboutin-pmc** [comment]
It works! So that was the thing I was missing here. For `pretty` to work with another format, you have to enable `debug: true`.

Thank you @gkushang,

**Comment by gkushang** [comment]
Sure. Closing the issue since it's resolved!
