### ISSUE TITLE
Parallel option not working with latest version of plugin

### ISSUE THREAD

**Issue by Vovanchik** [mavdi/grunt-cucumberjs#85]
Result **json** and **html** files are not created, when tests are run in parallel mode using following command:
`grunt cucumber-tests --parallel scenarios`

When the same test suite is run without  `executeParallel: 'true'` option everything work's as expected. 

Here is an example of configuration file which is used to run TCs:

```
        cucumberjs: {
            src: ['src/test/features/'],
            options: {
                format: 'html',
                output: 'target/cucumber-reports/test-report.html',
                theme: 'bootstrap',
                debug: true,
                executeParallel: 'true'
            }
        }
```

**Comment by BogdanLivadariu** [comment]
@Vovanchik 
```js
executeParallel: 'true'
```
should be 
```js
executeParallel: true
```

as it should be a type boolean, not a type string

```js
        cucumberjs: {
            src: ['src/test/features/'],
            options: {
                format: 'html',
                output: 'target/cucumber-reports/test-report.html',
                theme: 'bootstrap',
                debug: true,
                executeParallel: true
            }
        }
```

**Comment by Vovanchik** [comment]
Copy-paste error. 

Added as boolean, anyway file is not created and result is printed to console output instead of file.

**Comment by BogdanLivadariu** [comment]
@Vovanchik  I remember I had the same problem some time ago ...
what I did, is to print the entire console into a file, and scrap its content for the JSON results

`grunt cucumber-tests --parallel scenarios > out.log` _> then scrape the file

**Comment by Vovanchik** [comment]
This is workaround which I used as well. ;)

I register this issue to ensure that bug can be fixed.

**Comment by Vovanchik** [comment]
Can't reproduce right now. closing issue.
