### ISSUE TITLE
Html report wont open some scenario details but opens others

### ISSUE THREAD

**Issue by shaneobrien20** [mavdi/grunt-cucumberjs#86]
Hey guys,

Found an issue where if you click on the feature in the html report it expands, but if you click on the scenario under it nothing happens. Found that this only happens for some features. 

After some digging i found that this only happens when you have quite a large amount of features, but also quite a large amount of scenarios under a feature. The specific issue is in relation to the id used to target the div. It uses a system like this: 

feature 2 and scenario 22 would be represented by `#collapseScenario222` 
The issue rears its head if you also have 22 features, and then 2 scenarios under feature 22, its still represented by `#collapseScenario222`. This obviously causes problems...

I managed to fix this very easily by separating the feature number from the scenario number like so: `#collapseScenario2_22` and `#collapseScenario22_2`.

The fix needs to be in the template files. I am using bootstrap so i changed all instances of `<%= featureIndex %><%= scenarioIndex %>` in 'templates/bootstrap/features.tmpl' to `<%= featureIndex %>_<%= scenarioIndex %>`. I guess you could just do the same for the other feature files?

Seems to work well for me anyway. Thought someone involved in this project would like to know and that it might help others.

Thanks guys, great project.
Shane

**Comment by gkushang** [comment]
Hey @shaneobrien20 that is great catch! Nice explanation too, definitely helps the community. Will plan to fix in the [html-reporter](https://www.npmjs.com/package/cucumber-html-reporter). Thanks!

**Comment by shaneobrien20** [comment]
No problem guys keep up the good work.

**Comment by gkushang** [comment]
fixed and released `grunt-cucumberjs@0.10.4`. Please do the clean install.
