### ISSUE TITLE
rerun

### ISSUE THREAD

**Issue by Crispin1988** [mavdi/grunt-cucumberjs#89]
Is this still a feature?
- Run failed scenarios by passing --rerun=path/to/@rerun.txt grunt option

I can generate the file of failed scenarios but cannot rerun them by passing the argument on the command line.

The lines committed here [https://github.com/mavdi/grunt-cucumberjs/commit/34a8157c62c49d10e574670e45c51f3380602137] have been removed or refactored somehow?

I've implemented my own grunt task to rerun from the file but I'm not able to specify individual scenario lines, rather entire feature files. Is this a symptom of the way the parameters are parsed (the line numbers are denoted after a colon) or was the the ability to rerun the individual scenarios not part of the rerun option previously anyway?

Thanks

**Comment by gkushang** [comment]
published grunt-cucumberjs@0.10.7
